### ISSUE TITLE
Use of Rf_error() in C

### ISSUE THREAD

**Issue by jeroen** [rorynolan/ijtiff#5]
You use a lot of this:

```c
 Rf_error("12-bit images are not supported. ",  "Try converting your image to 16-bit.");
 TIFFClose(tiff);
 UNPROTECT(to_unprotect);
 return R_NilValue;
```

There are a few problems here. You should know that `Rf_error` immediately jumps back to the console. So lines 2-4 can never be reached. 

Also you don't have to `UNPROTECT` or `return` anything in case of an error. Moreover afaik `Rf_error()` only supports one string argument. So you probably want to do something like:

```c
 TIFFClose(tiff);
 Rf_error("12-bit images are not supported. Try converting your image to 16-bit.");
```

**Comment by rorynolan** [comment]
* __You should know that Rf_error immediately jumps back to the console. So lines 2-4 can never be reached. Also you don't have to UNPROTECT or return anything in case of an error.__
  - I suspected that this was the case but I wasn't sure so I had lines 2-4 as a just in case. These are now cleaned away, thanks.

* __Moreover afaik Rf_error() only supports one string argument.__
  - I knew this, I'm only using one argument, I don't have a comma within the parentheses. I'm using 
```c
Rf_error("12-bit images are not supported. "  
         "Try` converting your image to 16-bit.");
```
I'm using the fact that two string literals separated by a space in C/C++ with no comma between has the effect of just concatenating them. I do this to make the code cleaner.

* __You probably want to do something like:__
```c
TIFFClose(tiff);
 Rf_error(". . .");
```
  - You're right that I should do `TIFFClose(tiff);` before calling `Rf_error`.

All of this is done now.
Thanks again :-)
